# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Master.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(421, 499)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(421, 499))
        Form.setMaximumSize(QtCore.QSize(421, 499))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setMinimumSize(QtCore.QSize(0, 0))
        self.Tabs.setMaximumSize(QtCore.QSize(9999, 99999))
        self.Tabs.setObjectName("Tabs")
        self.tab_hosts = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_hosts.sizePolicy().hasHeightForWidth())
        self.tab_hosts.setSizePolicy(sizePolicy)
        self.tab_hosts.setObjectName("tab_hosts")
        self.combo_netmask = QtWidgets.QComboBox(self.tab_hosts)
        self.combo_netmask.setGeometry(QtCore.QRect(70, 9, 46, 25))
        self.combo_netmask.setObjectName("combo_netmask")
        self.combo_netmask.addItem("")
        self.combo_netmask.addItem("")
        self.combo_netmask.addItem("")
        self.lable_netmask = QtWidgets.QLabel(self.tab_hosts)
        self.lable_netmask.setGeometry(QtCore.QRect(9, 9, 57, 25))
        self.lable_netmask.setObjectName("lable_netmask")
        self.btn_scan = QtWidgets.QPushButton(self.tab_hosts)
        self.btn_scan.setGeometry(QtCore.QRect(250, 10, 80, 25))
        self.btn_scan.setObjectName("btn_scan")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_hosts)
        self.splitter_2.setGeometry(QtCore.QRect(10, 60, 197, 25))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_network = QtWidgets.QLabel(self.splitter_2)
        self.label_network.setObjectName("label_network")
        self.line_network = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_network.sizePolicy().hasHeightForWidth())
        self.line_network.setSizePolicy(sizePolicy)
        self.line_network.setObjectName("line_network")
        self.list_ip = QtWidgets.QListWidget(self.tab_hosts)
        self.list_ip.setGeometry(QtCore.QRect(90, 90, 221, 351))
        self.list_ip.setObjectName("list_ip")
        self.progressBar = QtWidgets.QProgressBar(self.tab_hosts)
        self.progressBar.setGeometry(QtCore.QRect(250, 60, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.Tabs.addTab(self.tab_hosts, "")
        self.tab_auth = QtWidgets.QWidget()
        self.tab_auth.setObjectName("tab_auth")
        self.list_ip_2 = QtWidgets.QListWidget(self.tab_auth)
        self.list_ip_2.setGeometry(QtCore.QRect(0, 0, 171, 201))
        self.list_ip_2.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.list_ip_2.setObjectName("list_ip_2")
        self.list_ip_3 = QtWidgets.QListWidget(self.tab_auth)
        self.list_ip_3.setGeometry(QtCore.QRect(230, 0, 171, 201))
        self.list_ip_3.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.list_ip_3.setObjectName("list_ip_3")
        self.btn_to_auth = QtWidgets.QPushButton(self.tab_auth)
        self.btn_to_auth.setGeometry(QtCore.QRect(180, 40, 41, 25))
        self.btn_to_auth.setObjectName("btn_to_auth")
        self.btn_no_auth = QtWidgets.QPushButton(self.tab_auth)
        self.btn_no_auth.setGeometry(QtCore.QRect(180, 110, 41, 25))
        self.btn_no_auth.setObjectName("btn_no_auth")
        self.list_success = QtWidgets.QListWidget(self.tab_auth)
        self.list_success.setGeometry(QtCore.QRect(230, 230, 171, 211))
        self.list_success.setObjectName("list_success")
        self.btn_auth = QtWidgets.QPushButton(self.tab_auth)
        self.btn_auth.setGeometry(QtCore.QRect(40, 380, 83, 25))
        self.btn_auth.setObjectName("btn_auth")
        self.splitter = QtWidgets.QSplitter(self.tab_auth)
        self.splitter.setGeometry(QtCore.QRect(20, 221, 142, 126))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.line_user = QtWidgets.QLineEdit(self.splitter)
        self.line_user.setObjectName("line_user")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.line_pass = QtWidgets.QLineEdit(self.splitter)
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.line_pass_again = QtWidgets.QLineEdit(self.splitter)
        self.line_pass_again.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass_again.setObjectName("line_pass_again")
        self.Tabs.addTab(self.tab_auth, "")
        self.tab_controls = QtWidgets.QWidget()
        self.tab_controls.setObjectName("tab_controls")
        self.list_ip_4 = QtWidgets.QListWidget(self.tab_controls)
        self.list_ip_4.setGeometry(QtCore.QRect(0, 0, 221, 271))
        self.list_ip_4.setObjectName("list_ip_4")
        self.list_success_controls = QtWidgets.QListWidget(self.tab_controls)
        self.list_success_controls.setGeometry(QtCore.QRect(250, 30, 131, 61))
        self.list_success_controls.setObjectName("list_success_controls")
        self.btn_shutdown = QtWidgets.QPushButton(self.tab_controls)
        self.btn_shutdown.setGeometry(QtCore.QRect(40, 300, 83, 25))
        self.btn_shutdown.setObjectName("btn_shutdown")
        self.btn_restart = QtWidgets.QPushButton(self.tab_controls)
        self.btn_restart.setGeometry(QtCore.QRect(40, 340, 83, 25))
        self.btn_restart.setObjectName("btn_restart")
        self.line_check = QtWidgets.QLineEdit(self.tab_controls)
        self.line_check.setEnabled(False)
        self.line_check.setGeometry(QtCore.QRect(260, 130, 113, 25))
        self.line_check.setObjectName("line_check")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_controls)
        self.splitter_3.setGeometry(QtCore.QRect(240, 300, 142, 126))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        self.label_4.setObjectName("label_4")
        self.line_user_controls = QtWidgets.QLineEdit(self.splitter_3)
        self.line_user_controls.setObjectName("line_user_controls")
        self.label_5 = QtWidgets.QLabel(self.splitter_3)
        self.label_5.setObjectName("label_5")
        self.line_pass_controls = QtWidgets.QLineEdit(self.splitter_3)
        self.line_pass_controls.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass_controls.setObjectName("line_pass_controls")
        self.label_6 = QtWidgets.QLabel(self.splitter_3)
        self.label_6.setObjectName("label_6")
        self.line_pass_again_controls = QtWidgets.QLineEdit(self.splitter_3)
        self.line_pass_again_controls.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass_again_controls.setObjectName("line_pass_again_controls")
        self.splitter_4 = QtWidgets.QSplitter(self.tab_controls)
        self.splitter_4.setGeometry(QtCore.QRect(240, 180, 142, 42))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_7 = QtWidgets.QLabel(self.splitter_4)
        self.label_7.setObjectName("label_7")
        self.line_check_2 = QtWidgets.QLineEdit(self.splitter_4)
        self.line_check_2.setObjectName("line_check_2")
        self.Tabs.addTab(self.tab_controls, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.list_ip_5 = QtWidgets.QListWidget(self.tab)
        self.list_ip_5.setGeometry(QtCore.QRect(60, 10, 256, 192))
        self.list_ip_5.setObjectName("list_ip_5")
        self.line_destination = QtWidgets.QLineEdit(self.tab)
        self.line_destination.setGeometry(QtCore.QRect(10, 305, 331, 19))
        self.line_destination.setObjectName("line_destination")
        self.line_source = QtWidgets.QLineEdit(self.tab)
        self.line_source.setGeometry(QtCore.QRect(10, 261, 331, 19))
        self.line_source.setObjectName("line_source")
        self.btn_backup = QtWidgets.QPushButton(self.tab)
        self.btn_backup.setGeometry(QtCore.QRect(140, 360, 83, 25))
        self.btn_backup.setObjectName("btn_backup")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 64, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 284, 81, 17))
        self.label_9.setObjectName("label_9")
        self.Tabs.addTab(self.tab, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Abu-Trika"))
        Form.setToolTip(_translate("Form", "Abu-Trika"))
        self.combo_netmask.setItemText(0, _translate("Form", "24"))
        self.combo_netmask.setItemText(1, _translate("Form", "16"))
        self.combo_netmask.setItemText(2, _translate("Form", "8"))
        self.lable_netmask.setText(_translate("Form", "netmask "))
        self.btn_scan.setText(_translate("Form", "Scan "))
        self.label_network.setText(_translate("Form", "Network"))
        self.line_network.setPlaceholderText(_translate("Form", "192.168.1.1"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_hosts), _translate("Form", "Hosts"))
        self.btn_to_auth.setText(_translate("Form", ">>"))
        self.btn_no_auth.setText(_translate("Form", "<<"))
        self.btn_auth.setText(_translate("Form", "Auth"))
        self.label.setText(_translate("Form", "username :"))
        self.line_user.setPlaceholderText(_translate("Form", "root"))
        self.label_2.setText(_translate("Form", "password :"))
        self.line_pass.setPlaceholderText(_translate("Form", "password"))
        self.label_3.setText(_translate("Form", "password again :"))
        self.line_pass_again.setPlaceholderText(_translate("Form", "password"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_auth), _translate("Form", "auth"))
        self.btn_shutdown.setText(_translate("Form", "shutdown"))
        self.btn_restart.setText(_translate("Form", "restart"))
        self.label_4.setText(_translate("Form", "username"))
        self.label_5.setText(_translate("Form", "password"))
        self.label_6.setText(_translate("Form", "password again :"))
        self.label_7.setText(_translate("Form", "write above numbers"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_controls), _translate("Form", "controls"))
        self.btn_backup.setText(_translate("Form", "Backup"))
        self.label_8.setText(_translate("Form", "source"))
        self.label_9.setText(_translate("Form", "destination"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("Form", "Backup"))

